equation_of_state:
  name: "Equation of State"

  module: mof_eos

  mlips:
    - mace
    # - sevennet
    - mace-mpa

  structs: get_mof_files

  score:
    inputs: metrics
    calc: combine_eos_metrics

    metrics:
      B:
        inputs: bulk_moduli
        calc: get_mean_errors
        plot: parity_scatter
        bulk_moduli:
          calc: get_bulk_moduli
          plot:
            - plot_eos
            - struct

      E_0:
        inputs: E_0s
        calc: get_mean_errors
        plot: parity_scatter
        E_0s:
          calc: get_E_0s
          plot:
            - plot_eos
            - struct

      V_0:
        inputs: V_0s
        calc: get_mean_errors
        plot: parity_scatter
        V_0s:
          calc: get_V_0s
          plot:
            - plot_eos
            - struct
