homonuclear_diatomics:
  name: "Homonuclear Diatomics"

  module: homonuclear_diatomics

  mlips:
    - mace_mp
    - mace_mpa

  structs: get_structs

  score:
    inputs: metrics
    calc: combine_metrics

    metrics:
      energy:
        inputs: energy_values
        calc: get_energy_metric
        plot: bar
        energy_values:
          calc: get_energy_values
          plot:
            - energy_plot
