name: docker-image
on:
  push:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    # if: github.repository == 'ddmms/ml-peg'
    permissions:
      packages: write
      contents: read
    steps:
      - name: "Login to ghcr"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./containers/Dockerfile
          platforms: linux/${{ matrix.architecture }}
          push: true
          tags: |
            ghcr.io/elliottkasoar/ml-peg-app:${{ matrix.architecture }}-latest
            ghcr.io/elliottkasoar/ml-peg-app:${{ matrix.architecture }}-${{ github.sha }}
